# 是否执行上传备份脚本（true/false）
ENABLE_UPLOAD_SCRIPT=false
# 是否启用上传备份脚本中的在线切片功能（true/false）
ENABLE_WEBCLIP=false # 修改后需要重启容器以生效

# ===============================
# 以下配置仅在启用在线切片功能时才生效
# ===============================
# 在线切片服务监听的端口
WEBCLIP_PORT=8186

# ===============================
# 以下配置仅在执行上传备份脚本时才生效
# ===============================
# 服务器名称
server_name="甲骨文-1-debian-1"
# 需要上传视频文件的录制平台。录播姬或者biliup，可以为多个
update_servers=(
  #"biliup"
  "录播姬"
)
# 是否启用上传备份脚本中视频压制（true/false）
ENABLE_DANMAKU_OVERLAY=false
# 是否将 FLV 文件转换为 mp4 格式（true/false），若关闭则后续仍使用原 flv 文件
# 注意！，如果不转换为mp4不能进行弹幕压制
CONVERT_FLV_TO_MP4=true

# 上传简介模板，可使用占位符 {title} 和 {platform} 表示直播标题和录制平台
# 其余内容为固定文本，支持多行
UPLOAD_DESC_TEMPLATE='直播间标题：{title}
录制平台：{platform}

括弧笑频道主页：
bilibili
顶级尼鸡塔结晶
https://space.bilibili.com/296620370
高机动持盾军官
https://space.bilibili.com/32223456
acfun
蘑菇的括弧笑
https://www.acfun.cn/u/12909228
鬼屋神狙会
https://www.acfun.cn/u/73177808
youtube
蘑菇的刮弧笑
https://www.youtube.com/@蘑菇的刮弧笑

括弧笑直播间地址：
bilibili
https://live.bilibili.com/1962720

使用录播姬和biliup录制上传，有问题请站内私信联系xct258
https://space.bilibili.com/33235987

项目地址：
https://github.com/xct258/khx-live

非常感谢录播姬和biliup项目
录播姬
https://github.com/BililiveRecorder/BililiveRecorder
biliup
https://github.com/biliup/biliup'
# 是否启用上传备份脚本中投稿视频（true/false）
ENABLE_VIDEO_UPLOAD=false
# 是否启用上传备份脚本中 rclone 网盘备份（true/false）
ENABLE_RCLONE_UPLOAD=false
# 每天定时执行上传备份脚本的时间（24小时制，例如 02:00）
SCHEDULE_SLEEP_TIME="01:30"
# 是否启用自动清理旧视频（true/false），超过保留天数的视频将被删除
ENABLE_CLEANUP=false
# 视频保留天数
RETENTION_DAYS=7
# 设置视频源文件夹路径，会处理设置目录中的的文件夹里的视频，不会处理设置目录中的视频
source_folders=(
  "/rec/biliup/video"
  "/rec/录播姬/video"
  # 可以继续添加其它目录
)
# 上传用的 cookies 文件路径
biliup_up_cookies="/rec/cookies/bilibili/cookies-烦心事远离.json"
# 录播姬同步用的 cookie JSON 文件路径
record_cookie_json="/rec/cookies/bilibili/cookies-xct258-2.json"
# DanmakuFactory转换xml文件为ass文件时的透明度（1-255，255为不透明）
DanmakuFactory_opacity=155